apiVersion: v1
kind: Service
metadata:
  name: genericdaemon
spec:
  selector:
    statefulset: genericdaemon-statefulset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
