apiVersion: batch.tutorial.kubebuilder.io/v1
kind: GenericDaemon
metadata:
  name: genericdaemon
spec:
  image: httpd
  label: jupyter-notebook
  replica: 2
  serviceport: 8888
  protocol: "TCP"
  servicetype: "LoadBalancer"
