# permissions to do viewer genericdaemons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: genericdaemon-viewer-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - genericdaemons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - genericdaemons/status
  verbs:
  - get
